[WIP] Fix/wishlist bug
Wishibam/SyliusWishlistPlugin pull request #3
Opened 2022-12-23 14:58 UTC by guillaumevdpsensio

2023-01-05 10:57 UTC, Nek- requested changes
Pas mal de taff qui va dans le bon sens, j'aime particulièrement le fait que tu ais ajouté un schéma. Cependant j'ai quelques remarques, je te laisse voir cela.

2023-01-05 10:57 UTC, Nek- commented on src/Context/WishlistContext.php
> +        $this->cookies = $this->requestStack->getMainRequest()->cookies;
Il faut enregistrer la request stack dans les attributs et récupérer les cookies quand ils sont utilisés. C'est précisément parce que Symfony manage plusieurs requests que la request stack existe, est stateful et doit être utilisée.

-> Récupération des cookies au moment de leur utilisation.

D'ailleurs perso j'aurais conservé la request en paramètre de getWishlist

2023-01-05 10:57 UTC, Nek- commented on src/Controller/Action/AddProductToWishlistAction.php
> +        private string $wishlistCookieTokenName,
Faudra penser à modifier le composer.json pour spécifier que c'est compatible PHP 8.0+

2023-01-05 10:57 UTC, Nek- commented on src/Controller/Action/AddProductToWishlistAction.php
> +        $refererPathInfo = Request::create($referer)->getPathInfo();
Le create fait beaucoup de choses ça serait bien de l'éviter. Cela-étant dit pourquoi tu ne rediriges pas directement sur le referer ? Tu veux retirer le nom de domaine ?

Ce code un peu plus light a le même effet:

```php
$referer = parse_url($request->headers->get('referer'));
$referer = $referer['path'];
```

2023-01-05 10:57 UTC, Nek- commented on src/EventSubscriber/BindUserToAnonymousWishlistEventSubscriber.php
> +            SecurityEvents::INTERACTIVE_LOGIN => [['onRegisterOrLogin', self::AFTER_MERGE_WISHLIST_LISTENER_PRIORITY]],
Intéressant ces events, j'espère qu'ils sont lancés aussi au moment du login via oauth... Mais on pourra peut être voir cela dans un second temps vu que ça ne concerne que TVO de mémoire.

2023-01-05 10:57 UTC, Nek- commented on src/Helper/WishlistsMerger.php
> +            $intoWishlist->addWishlistProduct(clone $cookieWishlistProduct);
Hum le clone là je ne suis pas sûr du tout, un deepcopy configuré me plairait plus. Mais en tous les cas il faudrait au moins ajouter une méthode clone au produit pour faire supprimer son id... Et peut être que ce clone implique aussi de cloner d'autres objets en cascade (car le comportement par défaut c'est de reprendre les refs des objets descendants...)

2023-01-06 13:53 UTC, vinzlj commented on src/Controller/Action/AddProductToWishlistAction.php
> +        private string $wishlistCookieTokenName,
c'est déjà le cas

2023-01-06 13:58 UTC, vinzlj commented on src/Helper/WishlistsMerger.php
> +            $intoWishlist->addWishlistProduct(clone $cookieWishlistProduct);
on a besoin de cloner sinon ça fait bugger Doctrine

2023-01-06 15:10 UTC, Nek- commented on src/EventSubscriber/BindUserToAnonymousWishlistEventSubscriber.php
> +            SecurityEvents::INTERACTIVE_LOGIN => [['onRegisterOrLogin', self::AFTER_MERGE_WISHLIST_LISTENER_PRIORITY]],
Side note : je crois que ce correctif résout le pb: https://github.com/Wishibam/Ecommerce-sylius/pull/4675/files#diff-e0aeaf20449a86f651188526e6ad497a93e002be452d92892a49edf82fd55526R44

2023-01-06 15:11 UTC, Nek- commented on src/Helper/WishlistsMerger.php
> +            $intoWishlist->addWishlistProduct(clone $cookieWishlistProduct);
Ouais mais justement c'est pire là car tu clones un objet pour faire un nouvel item en db mais finalement c'est le même item car tu changes pas l'id....... Pour moi le comportement de doctrine est très _indéterminé_ ici. Je pense qu'il va créer un nouvel objet mais bon c'est bizarre quoi, et puis il va probablement pas le faire pour les objets descendants.

2023-01-09 10:53 UTC, guillaumevdpsensio commented on src/Helper/WishlistsMerger.php
> +            $intoWishlist->addWishlistProduct(clone $cookieWishlistProduct);
Personnellement, je pense que le `clone` est tout à fait valide. On veut justement copier l'objet en lui même, pas ses références, et garder les références de l'ancien objet pour le mapper sur le nouveau. Doctrine à l'air de parfaitement gérer ce cas là.

2023-01-09 14:07 UTC, vinzlj approved these changes

2023-01-09 14:22 UTC, vinzlj commented on src/Helper/WishlistsMerger.php
> +            $intoWishlist->addWishlistProduct(clone $cookieWishlistProduct);
On merge, on a besoin de tester ça vite, s'il faut modifier ensuite on pourra, même si je suis d'accord avec @guillaumevdpsensio  🙂

2023-01-09 14:22 UTC, merged